name: condaenv
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - boltons=23.0.0=py311hca03da5_0
  - brotlipy=0.7.0=py311h80987f9_1002
  - bzip2=1.0.8=h620ffc9_4
  - c-ares=1.19.0=h80987f9_0
  - ca-certificates=2024.8.30=hf0a4a13_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.15.1=py311h80987f9_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - comm=0.2.2=pyhd8ed1ab_0
  - conda=23.5.2=py311hca03da5_0
  - conda-content-trust=0.1.3=py311hca03da5_0
  - conda-libmamba-solver=23.5.0=py311hca03da5_0
  - conda-package-handling=2.1.0=py311hca03da5_0
  - conda-package-streaming=0.8.0=py311hca03da5_0
  - cryptography=39.0.1=py311h834c97f_2
  - debugpy=1.6.7=py311h313beb8_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - fmt=9.1.0=h48ca7d4_0
  - icu=68.1=hc377ac9_0
  - idna=3.4=py311hca03da5_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.29.0=pyh707e725_0
  - jedi=0.19.2=pyhff2d567_0
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - krb5=1.20.1=hf3e1bf2_1
  - libarchive=3.6.2=h62fee54_2
  - libcurl=8.1.1=h3e2b118_1
  - libcxx=14.0.6=h848a8c0_0
  - libedit=3.1.20221030=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_0
  - libiconv=1.16=h1a28f6b_2
  - libmamba=1.4.1=h1c5506f_1
  - libmambapy=1.4.1=py311h1c5506f_1
  - libnghttp2=1.52.0=h62f6fdd_1
  - libsodium=1.0.18=h27ca646_1
  - libsolv=0.7.22=h98b2900_0
  - libssh2=1.10.0=h02f6b3c_2
  - libxml2=2.10.3=h372ba2a_0
  - lz4-c=1.9.4=h313beb8_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.4.0=h39f12f2_0
  - packaging=23.0=py311hca03da5_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.37=h37e8eca_1
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=23.1.2=py311hca03da5_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pluggy=1.0.0=py311hca03da5_1
  - prompt-toolkit=3.0.48=pyha770c72_0
  - psutil=5.9.0=py311h80987f9_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycosat=0.6.4=py311h80987f9_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyopenssl=23.0.0=py311hca03da5_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.4=hb885b13_0
  - python-dateutil=2.9.0.post0=pyhff2d567_0
  - python.app=3=py311h80987f9_0
  - pyzmq=25.1.2=py311h313beb8_0
  - readline=8.2=h1a28f6b_0
  - reproc=14.2.4=hc377ac9_1
  - reproc-cpp=14.2.4=hc377ac9_1
  - requests=2.29.0=py311hca03da5_0
  - ruamel.yaml=0.17.21=py311h80987f9_0
  - setuptools=67.8.0=py311hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h80987f9_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=hb8d0fd4_0
  - toolz=0.12.0=py311hca03da5_0
  - tornado=6.4.1=py311h80987f9_0
  - tqdm=4.65.0=py311hb6e6a13_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.16=py311hca03da5_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.38.4=py311hca03da5_0
  - xz=5.4.2=h80987f9_0
  - yaml-cpp=0.7.0=hc377ac9_1
  - zeromq=4.3.5=h313beb8_0
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5a0b063_0
  - zstandard=0.19.0=py311h80987f9_0
  - zstd=1.5.5=hd90d995_0
prefix: /Users/vittoriostile/miniconda3
